// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZIvJca9gpDcwq3qSQOABgpBNSzJDgN3I',
    appId: '1:43228129606:web:374f3f97393f71bb989d47',
    messagingSenderId: '43228129606',
    projectId: 'my-sample-todo-app',
    authDomain: 'my-sample-todo-app.firebaseapp.com',
    storageBucket: 'my-sample-todo-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwSolAmaAPjzj9ldRmt0XdChv1bBXcH5M',
    appId: '1:43228129606:android:46bf7740e1d00918989d47',
    messagingSenderId: '43228129606',
    projectId: 'my-sample-todo-app',
    storageBucket: 'my-sample-todo-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVA3rBpJ2C4QGbAGFZgzOYhIQ1HHiaDy0',
    appId: '1:43228129606:ios:76c31e057141b09b989d47',
    messagingSenderId: '43228129606',
    projectId: 'my-sample-todo-app',
    storageBucket: 'my-sample-todo-app.appspot.com',
    iosClientId: '43228129606-skcfju9k3olh5ecttj1mlilmui1kiks8.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVA3rBpJ2C4QGbAGFZgzOYhIQ1HHiaDy0',
    appId: '1:43228129606:ios:76c31e057141b09b989d47',
    messagingSenderId: '43228129606',
    projectId: 'my-sample-todo-app',
    storageBucket: 'my-sample-todo-app.appspot.com',
    iosClientId: '43228129606-skcfju9k3olh5ecttj1mlilmui1kiks8.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoApp',
  );
}
